src/client/intercept/client/sqf/common_helpers.cpp
src/client/intercept/client/sqf/misc.cpp
src/client/intercept/client/sqf/misc.hpp

Fixing a number of compiler pointer errors on new function helpers

---

tools/build.py

Added ACE3 build.py to create intercept_core.pbo

---

src/client/intercept/client/sqf/uncategorized.cpp
src/client/intercept/client/sqf/uncategorized.hpp

My first PR for intercept, would be great if I could get some feedback if I'm doing something wrong here.

Added binary function wrappers

---

tools/setup.py

Removed CBA includes of course.
This is P drive setup only, no CMAKE solution generation.

Add ACE3 setup.py to prepare dev environment (P drive only)

---

src/client/intercept/client/sqf/uncategorized.cpp
src/client/intercept/client/sqf/uncategorized.hpp

And use helper function for `near_objects` wrappers as well as alternate syntax for `name` and `slider_set_position`.

Add slider, speed, importance and other unary wrappers

---

src/client/intercept/client/sqf/uncategorized.cpp
src/client/intercept/client/sqf/uncategorized.hpp

This is my first time even writing code in C++ so bare with me...

Reversed marker arguments and added set_marker_color

---

src/client/intercept/client/sqf/uncategorized.cpp
src/client/intercept/client/sqf/uncategorized.hpp

These are the wrappers for all the syntaxes of `getvariable`. As far as I tested they work alright.

getvariable wrappers

---

src/client/intercept/client/sqf/uncategorized.cpp
src/client/intercept/client/sqf/uncategorized.hpp

I'll be adding more commits as I go, just here so people can see what's been done already.

Adding tree view wrappers

---

src/client/intercept/client/sqf/uncategorized.cpp
src/client/intercept/client/sqf/uncategorized.hpp

I also tested it built without errors/warnings and it did.

Added more ctrl wrappers

---

src/client/intercept/client/sqf/uncategorized.cpp
src/client/intercept/client/sqf/uncategorized.hpp

Just working down the list. I'll be adding more to this PR.

Added more binary wrappers - no specific category

---

src/client/intercept/client/sqf/common_helpers.cpp
src/client/intercept/client/sqf/common_helpers.hpp
src/client/intercept/client/sqf/uncategorized.cpp
src/client/intercept/client/sqf/uncategorized.hpp

It's my first PR to Intercept so please review this with care :).
I'm not sure if creating a new __convert_to_integers_vector helper was the right choice or whether I should have stuck with __convert_to_numbers_vector instead.

Unary Tree View functions

---

src/client/intercept/client/sqf/uncategorized.cpp
src/client/intercept/client/sqf/uncategorized.hpp

Added on top of #73, so merge it first.

Fix full_crew wrapper

---

src/client/headers/client/sqf/uncategorized.hpp
src/client/intercept/client/sqf/uncategorized.cpp

Add unary wrappers

---

src/client/headers/client/sqf/uncategorized.hpp
src/client/intercept/client/sqf/uncategorized.cpp

Added particle wrappers

---

src/client/headers/client/sqf/uncategorized.hpp
src/client/intercept/client/sqf/uncategorized.cpp

Yay for not doing class work (or finishing it early).

Add pp_effect_destroy, task_description and task_hint unary wrappers

---

rv/addons/core/config.cpp
src/client/headers/shared/types.hpp
src/client/intercept/shared/types.cpp
src/host/loader/loader.cpp

Compatability update for Arma 1.66
I didn't test in 1.64 but i think it should also work there.
Also somehow lib.sqf is not executing in preInit.. I dunno why. I just called manually. Also that causes a crash if any Eventhandler is called and the invoker is not initialized.
Btw your slackin link is down :x

1.66 compat

---

src/client/headers/client/sqf/uncategorized.hpp
src/client/intercept/client/sqf/uncategorized.cpp

Not much, but it's something :)

Add create unit wrappers

---

.travis.yml
appveyor.yml
src/client/headers/shared/types.hpp
src/host/invoker/sqf_functions.cpp
src/host/invoker/sqf_functions.hpp
src/host/loader/loader.cpp
src/host/loader/loader.hpp

Also enables status checks on develop branch.

Refactor Loader

---

.editorconfig
appveyor.yml

Also set EditorConfig indentation_size to 2 for .yml files.

AppVeyor - Only build if files inside src/ directory changed

---

src/client/headers/client/sqf/intersects.hpp
src/client/intercept/client/sqf/intersects.cpp

I couldn't find an implementation for [checkVisibility](https://community.bistudio.com/wiki/checkVisibility), so I added it. Just copied implementation from intersects, hope it's ok.

Added checkVisibility

---

src/client/headers/client/sqf/common_helpers.hpp
src/client/headers/client/sqf/marker.hpp
src/client/headers/client/sqf/position.hpp
src/client/intercept/client/sqf/common_helpers.cpp
src/client/intercept/client/sqf/marker.cpp
src/client/intercept/client/sqf/position.cpp
src/host/extensions/extensions.cpp

I will use this to repair some of the other wrong implemented wrappers too..
(sorry for the commit stuff, this was on done on intercept/develop before, so I needed to create a new branch on my local repo first and arrrgggh)

Fix some implemetations and add some helper functions

---

src/client/headers/client/eventhandlers.hpp
src/client/intercept/client/eventhandlers.cpp

Added MP Eventhandlers to the new overhauled Eventhandler system.
Waiting for this being tested. @RZSenfo 
Already included in `develop` branch.

Added MP Eventhandlers

---

src/host/CMakeLists.txt
src/host/extensions/signing.cpp
src/host/extensions/signing.hpp
src/host/loader/loader.cpp

Will need binary rebuild because the gameState finder algo was broken on 32-bit.
I tested this on Linux server. and Arma stable 32/64 bit.

Fix linux library errors

---

src/host/invoker/invoker.cpp

Fix deadlock when using recursive invoker_lock

---

src/client/headers/client/client.hpp
src/client/headers/shared/client_types.hpp
src/client/headers/shared/functions.hpp
src/client/headers/shared/types.hpp
src/client/intercept/client/client.cpp
src/client/intercept/shared/types.cpp
src/host/extensions/export.cpp
src/host/extensions/export.hpp
src/host/invoker/eventhandlers.cpp
src/host/invoker/invoker.cpp
src/host/invoker/sqf_functions.cpp
src/host/invoker/sqf_functions.hpp
src/host/loader/loader.cpp
src/host/loader/loader.hpp

Also Register Function -> Register Command. Because Function != Command. And Intercept-CBA implements proper functions.

Rename exported functions according to convention

---

src/client/headers/shared/client_types.hpp
src/client/intercept/shared/client_types.cpp

@RZSenfo 
Do you want protection for allocations too? Would basically put a invoker_lock around each allocation.

Threadsafe GameValue

---

src/client/headers/shared/client_types.hpp
src/client/intercept/client/sqf/misc.cpp

corrected wrong binary function pointer
corrected wrong attribute of rv_particle_array
corrected wrong game_value cast of rv_particle_shape ( causing <no-shape> )

particle_array and particle_shape correction

---

src/client/headers/client/sqf/sqf.hpp
src/client/headers/shared/containers.hpp
src/client/headers/shared/vector.hpp
src/client/intercept/client/eventhandlers.cpp
src/client/intercept/client/sqf/group.cpp
src/client/intercept/client/sqf/waypoint.cpp

We were passing
`group setGroupId [nameFormat, [nameParam1, ..., nameParamN] ]`
instead of
`group setGroupId [nameFormat, nameParam1, ..., nameParamN]`
Also added a little bit of auto_array documentation and a convenience insert range function.

Fix setGroupID

---

.travis.yml
CMakeModules/cxx_compiler_functions.cmake
src/client/CMakeLists.txt
src/client/headers/shared/types.hpp
src/client/intercept/client/sqf/position.cpp
src/host/CMakeLists.txt
src/host/common/shared.hpp
src/host/extensions/CMakeLists.txt

Useful for local development and unit testing.
Probably not usable together with Arma.

Add support for building with Clang

---

src/client/headers/client/client.hpp
src/client/headers/shared/functions.hpp
src/client/headers/shared/types.hpp
src/client/intercept/client/client.cpp
src/client/intercept/shared/types.cpp
src/host/extensions/export.cpp
src/host/extensions/export.hpp
src/host/extensions/extensions.cpp
src/host/invoker/invoker.cpp
src/host/invoker/sqf_functions.cpp
src/host/invoker/sqf_functions.hpp
src/host/loader/loader.cpp
src/host/loader/loader.hpp

Add compound type support

---

.gitignore

Makes integration with CLion and other IDEs work better

Add cmake and output to gitignore

---

src/client/headers/shared/vector.hpp

Adds:
`vector3::dir_to`
`vector3::dir_to_2d`
`vector3::cos`
`vector3::angle`
`vector3::rotate_x`
`vector3::rotate_y`
`vector3::rotate_z`
`vector3::rotate_x_deg`
`vector3::rotate_y_deg`
`vector3::rotate_z_deg`
`vector2::dir_to`
`vector2::cos`
`vector2::angle`
`vector2::rotate`
`vector2::rotate_deg`

Added new vector operations: cos, angle and rotate

---

src/client/headers/shared/vector.hpp

* Added operations between vector2 and vector3 (z is assumed 0 for vector2).
* Fixed a mistake in `dir_to` member functions

Add operations between vector2 and vector3

---

src/client/headers/shared/vector.hpp

* Added ability to use indexes (0, 1, 2) with vectors via `operator[]`
* Added get_azimuth
* Added get_dir

Add new features to vectors

---

.github/workflows/ci.yml
src/host/loader/loader.cpp

Remove 32 bit Linux builds since it's no longer supported

---

src/client/headers/client/sqf/world.hpp
src/client/headers/shared/containers.hpp

Fixes #283 
Also add default constructor to rv_rain_params because it has too many parameters...

Fix rv_rain_parameters parameter ambiguity

---

src/client/headers/shared/containers.hpp

This is my first step into learning more about the intercept code base. All changes are related to documentation until I understand more. Wherever possible I tried to link to other docs, or add a url on the topic.

Doxygen documentation for class refcount_base, refcount, and ref
