- rv/addons/core/boot.sqf
~~Set a global variable when intercept is available and loaded~~
I reverted the added global variable, as there an `intercept_invoker_ok` variable set in the `missionNamespace`.
> Make intercept not load any extension by default.

- src/client/intercept/client/sqf/uncategorized.cpp
- src/client/intercept/client/sqf/uncategorized.hpp
My first intercept C++ PR, go easy. :grin: 
(I am totally not copying @BaerMitUmlaut)
Adds wrappers for:
- `nearestBuilding` alt syntax
- `nearObjects` main syntax (position or object)
- `nearObjects` alt syntax (position or object with array of string and number)
> Add near_objects wrapper and alt syntax for nearest_building

- src/client/intercept/client/sqf/intersects.cpp
- src/client/intercept/client/sqf/intersects.hpp
- src/client/intercept/client/sqf/uncategorized.cpp
- src/client/intercept/client/sqf/uncategorized.hpp
Fixes warnings reported by `sqf_wrapper_validation.py` on Travis:
```
WARNING: Found a default value ( = true) in implementation parameters (line_intersects_surfaces, intersects.cpp line 0)
WARNING: Found a default value ( = true) in implementation parameters (line_intersects_with, intersects.cpp line 0)
WARNING: Found a default value ( = "true") in implementation parameters (config_properties, uncategorized.cpp line 0)
WARNING: Found a default value ( = "NONE") in implementation parameters (create_vehicle, uncategorized.cpp line 0)
```
> Move default values to .hpp

- rv/addons/core/config.cpp
This is an alternative solution to that in #56.
It makes Intercept use CBA XEH framework for events. 
- All the complications derived from addon compatibility are offloaded to CBA.
- Reduced chances of incompatible content existing: if it works with CBA/ACE it works with Intercept
- Requires less maintainance
- CBA is required
- Some extra performance overhead 
- CBA doesn't handle `handleDamage`, probably because of it requiring a return value (Intercept will have to deal with the same problem anyway).
- Some events are not supported by XEH at the moment.
> Make Intercept use XEH

- tools/conversion_coverage.py
#83 changed the path of the header files. This makes the coverage reporting script find the declarations of all sqf function pointers again.
> Fix Coverage reporting triggering a build failure

- .gitignore
- rv/addons/core/boot.sqf
- rv/addons/core/config.cpp
- rv/addons/core/lib.sqf
- src/host/extensions/extensions.cpp
- src/host/extensions/extensions.hpp
- src/host/extensions/search.cpp
- src/host/extensions/search.hpp
Client plugins are now limited to being loaded from specific mod folders, in which they will have a folder called intercept. That folder will contain plugin dlls. Plugins are referred to by their dll name, minus the file extension.
For example:
`"intercept" callExtension "load_extension:example_dll";`
> Added path limiting to client module loading.

- rv/addons/core/config.cpp
Fixes #101
Also:
Modified Control Braces to match Coding Standarts
Fixed double semicolon warning of Mikeros tools
> Fixed preInit not executing

- src/client/headers/client/sqf/uncategorized.hpp
That's an error that shows as soon as you want to compile the example plugins.
Note: the order of this constructor is RBGA which is consistent with what has already been written in the file but this looks like a bug to me (shouldn't all of those constructors use RGBA instead?)
> Fix the "cannot convert from 'initializer list' to 'rv_color'" error.

- src/client/headers/client/sqf/uncategorized.hpp
The color order of rv_color is stored internally as RBGA, which is probably a bug.
This will work fine as long as all the values are passed at once because the `game_value` operator uses the same order as the constructor but if someone wants to access particular color components, they will access the wrong components.
This PR assumes PR #117 has already been merged.
> rv_color order should be RGBA

- src/host/loader/loader.cpp
There seem to be many changes, at first sight, but they boil down to adding two `placeholder` variables at the start of `gs*` structures and fixing some structures' sizes.
The other changes stem from the offsets in the comments that have all changed. Maybe these comments should be removed in the future.
> Fix crash with Arma v1.68.

- .gitignore
- src/client/headers/intercept.hpp
- src/client/headers/shared/functions.hpp
- src/client/headers/shared/pool.hpp
- src/client/headers/shared/types.hpp
- src/client/intercept/client/client.cpp
- src/client/intercept/client/sqf/intersects.cpp
- src/client/intercept/client/sqf/uncategorized.cpp
- src/client/intercept/shared/client_types.cpp
- src/client/intercept/shared/types.cpp
- src/host/extensions/export.cpp
- src/host/extensions/export.hpp
- src/host/extensions/extensions.cpp
- src/host/extensions/extensions.hpp
- src/host/invoker/eventhandlers.cpp
- src/host/invoker/invoker.cpp
- src/host/loader/loader.cpp
- src/host/loader/loader.hpp
Adds Generic Arma Allocator for RString and Arrays.
Adds Pool Allocator for GameData types
These allocators provide direct access to the Engine Allocator. Meaning we no longer have to wait for our allocated objects to become unused. Because Arma can now deallocate our allocated objects and we can also deallocate Arma objects.
Also includes new r_string implementation that mirrors the real engine type more closely
Also provides correctish Implementation of RefCount class so we don't need to emulate refcounting ourselves anymore.
> Allocator Overhaul

- .gitignore
- tools/build.py
- Title
- Add all files in `rv/` folder to .gitignore except `rv/addons/` folder - previously only Win32 build stuff, now catches everything
_Already included in v0.8.0 package._
> Fix pboprefix missing \rv\

- src/client/headers/client/sqf/misc.hpp
- src/client/intercept/client/sqf/misc.cpp
The existing implementation for drawIcon3D was missing the text align parameter and draw off screen parameter. This adds those 2 parameters. They are optional, and default to "center" and false respectively.
> Added extra parameters to drawIcon3D

- tools/sqf_wrapper_validation.py
Finds same amount of declarations so shouldn't make it leave out anything.
> Ignore colon in ternary operator when validating declarations

- src/host/extensions/search.cpp
- src/host/invoker/invoker.cpp
- src/host/loader/loader.cpp
Debug logs were creating dozens of gigabytes of useless logfiles.
If you really need them because you are debugging you work with a self compiled build anyway and can just enable what you need.
Decreasing the easylogging loglevel to not print debug messages is not enough. As the loglevel is set at runtime. The compiler can't know the level at compiletime. Meaning even if debug logging is disabled the log function is still called. Which is a huge performance concern in stuff like Eventhandlers or invoker_lock
> Disable all spaming debug logs

- src/client/headers/client/sqf/core.hpp
- src/client/intercept/client/sqf/core.cpp
- src/client/intercept/client/sqf/uncategorized.cpp
- binary__isequalto__any__any__ret__bool
- binary__isequaltype__any__any__ret__bool
- binary__isequaltypeall__array__any__ret__bool
- binary__isequaltypeany__any__array__ret__bool
- binary__isequaltypearray__array__array__ret__bool
- binary__isequaltypeparams__any__array__ret__bool
- binary__spawn__any__code__ret__script
I decided to implement the isEqual* wrappers because they are very useful and should have no huge performance impact. All they are doing in engine side is basically comparing numbers.
We can already do isEqualTo and isEqualType using our methods. But they are clunky and in the end do the same as the in-engine solutions just more complicated.
@RZSenfo requested `spawn` and I see this being useful to easilly launch tasks you don't care about when they complete.
> Added spawn and isEqual* Wrappers

- src/client/headers/shared/containers.hpp
- src/client/headers/shared/types.hpp
- src/client/intercept/shared/types.cpp
Current r_string move constructor still increases/modifies the refcount.
This add's a swap function that doesn't modify refcount. Thus faster
> Ref swap for faster r_string move construct

- .travis.yml
- src/client/headers/client/eventhandlers.hpp
- src/client/headers/client/sqf/core.hpp
- src/client/headers/client/sqf/ctrl.hpp
- src/client/headers/shared/containers.hpp
- src/client/headers/shared/types.hpp
- src/client/intercept/CMakeLists.txt
- src/client/intercept/client/eventhandlers.cpp
- src/client/intercept/client/sqf/core.cpp
- src/client/intercept/client/sqf/ctrl.cpp
- src/client/intercept/shared/types.cpp
- src/host/extensions/extensions.cpp
- src/host/extensions/extensions.hpp
- src/host/invoker/sqf_functions.cpp
- src/host/loader/loader.cpp
- src/host/loader/loader.hpp
- Made GameState class publicly accessible (First parameter to a RSQF function is currently a uintptr_t. That really is a `const GameState*`)
- Added Safe conversions thingy. Define `INTERCEPT_SAFE_CONVERSIONS` and conversions to invalid types (For example trying to convert a string to a number) will throw an exception (https://github.com/intercept/intercept/pull/194/commits/89caa939299c771c749053f4c8fc2927133fad78#diff-205e20fbe0dd07548a5e9185a3bf00f6R594)
- Fixed off by one error when trying to get a Array element out of a GameValue (https://github.com/intercept/intercept/pull/194/commits/89caa939299c771c749053f4c8fc2927133fad78#diff-205e20fbe0dd07548a5e9185a3bf00f6L662) If you try to get value[2] out of a array with 2 elements this safety check will fail and it will try to access the …
> Accessible Game State and Other misc

- src/client/headers/shared.hpp
- src/client/headers/shared/containers.hpp
- src/client/headers/shared/types.hpp
- src/client/intercept/client/client.cpp
- src/client/intercept/client/sqf/core.cpp
- src/client/intercept/shared/types.cpp
- src/host/common/easyloggingc++.hpp
- src/host/common/shared.hpp
- src/host/common/targetver.h
- src/host/extensions/extensions.cpp
- src/host/extensions/search.cpp
- src/host/invoker/invoker.cpp
- src/host/loader/loader.cpp
Another huge PR ^^
- Allow to directly set local variables to the local script's scope which is being used for sqf::call
- Fix mapStringToClass not setting existing items on insert
- add i_ref (refcount wrapper for IRef's used by Debugger Interfaces)
- add r_string::substr which returns string_view
- add map_string_to_class::remove
- Remove windows.h include from plugin header files
- Add stack_array (auto_array with push/pop functions)
- Fixed ignored code signing cert failures
- Fix number sign missmatch warning when compiling containers.hpp
Ported stuff from ArmaDebugEngine
- Implement I_debug_value (Mostly useless. But we need it implemented to keep correct vtable inheritance)
- Correctly implement game_data_namespace (Old one was just a placeholder)
> Make Variable namespaces accessible

- CMakeInclude.txt
- src/client/headers/client/sqf/config.hpp
- src/client/headers/shared/containers.hpp
- src/client/headers/shared/types.hpp
- src/client/intercept/client/sqf/config.cpp
- src/client/intercept/client/sqf/core.cpp
Ability to construct `ref` from convertible ref's.
Code style cleanup
Added `game_value::get_as`. Can be used to convert game_value to game_data more easily. Like `game_value.get_as<game_data_object>()`
Optimize sqf::call
Don't reallocate temp variable names everytime.
Take missionNamespace directly from gameState instead of calling the SQF command.
> Add config_entry iterator

- src/host/extensions/search.cpp
@dedmen on Slack:
> https://github.com/intercept/intercept/blob/39549e5ebdb367e79220df7b610fbb9ec1944f84/src/host/extensions/search.cpp#L50
Bug. Seperated by null chars. This outputs a string containing many strings wiht nullchars inbetween. Might not matter if the functions that search the command line use the strings length instead of stopping at first null char. But still bad.
Fix
```
while (std::getline(cmdline, line, '\0')) {
file_contents += line;
file_contents.push_back(' '); //#TODO can linux even have more than one line?
}
```
> Anyone feel free to PR. I can't right now (edited)
> Fix search null char separation

- .travis.yml
target_link_options is only available on CMake 3.13 and above
> Use CMake 3.14 on Travis instead of default 3.9.2

- src/client/intercept/client/client.cpp
Removed `inline` from `lock()`/`unlock()` because it might get optimized away as discussed on Slack.
> Removed inline from lock/unlock

- src/host/common/dispatch.hpp
```
src\host\common\dispatch.hpp(16): error C3615: constexpr function 'intercept::controller_module::controller_module' cannot result in a constant expression
src\host\common\dispatch.hpp(16): note: failure was caused by call of undefined function or one not declared 'constexpr'
src\host\common\dispatch.hpp(16): note: see usage of 'std::mutex::mutex'
```
> Fix compilation error with VS2019

- src/host/extensions/search.cpp
GetLibraryProcAddress is called with const char* arguments, but PSTR is char*, casting const char* to char* won't be allowed anymore in C++20
> Fixed casting const char* to char*

- src/client/headers/shared/vector.hpp
1. It didn't handle the case where magnitude could be zero (in Arma it returns [0,0,0] in this case)
2. Why take the abs of a positive number? it was pointless.
> Fixed vector normalize

- src/client/headers/client/eventhandlers.hpp
- src/client/intercept/client/eventhandlers.cpp
All event handlers have been updated.
In addition, the "random number generation" method for UIDs has been changed. The previous method could have collisions and was unsafe. The new one guarantees that you can successively create up to `33'554'432` event handlers of a certain type (object, ctrl, display, mission, MP) in one mission with no collisions.
Of course, the new method is not perfect either. For a perfect solution, you need to know the event handler ID before creating it, which is not possible in Arma at the moment.
> Update and fix event handlers

- src/client/headers/client/sqf/position.hpp
- src/client/headers/client/sqf/world.hpp
- src/client/intercept/client/sqf/position.cpp
- src/client/intercept/client/sqf/world.cpp
These commands are actually 2D anyway. The value of Z is ignored.
> Add 2d vector variants to some commands

- src/host/loader/CMakeLists.txt
- src/host/loader/loader.cpp
This change is required to support the new compiler that began being
used with the 2.08 v18+ versions of the performance branch on linux x64
> loader: Account for multiple memory regions in maps for linux x64

- src/client/headers/client/sqf/common_helpers.hpp
- src/client/headers/client/sqf/core.hpp
- src/client/headers/client/sqf/inventory.hpp
- src/client/headers/shared/client_types.hpp
- src/client/headers/shared/containers.hpp
- src/client/headers/shared/types.hpp
- src/client/intercept/client/client.cpp
- src/client/intercept/client/sqf/core.cpp
- src/client/intercept/client/sqf/inventory.cpp
- src/client/intercept/shared/types.cpp
- src/host/invoker/invoker.cpp
To-do: 
Sample test (RSQF):
SQF:
```sqf
testFn "ppBloom"
```
```cpp
game_value test_fn(game_value_parameter _id) {
auto vidOpts = get_video_options();
for (auto& opt : vidOpts) {
system_chat(str({ opt.key, opt.value }));
}
auto v = vidOpts.find(_id);
if (v)
return v->value;
else
return "not found";
}
```
> Added support for hashmap type

- src/client/headers/shared/client_types.hpp
- src/client/headers/shared/types.hpp
I've also removed the optimize pragma for Clang. Because it produces this error:
```
intercept\src\client\headers\shared/types.hpp:713:17: error: '#pragma optimize' can only appear at file scope
#pragma optimize("", on)
^
```
Clang is used by the Visual Studio extension "Struct Layout", which I use a lot:
https://marketplace.visualstudio.com/items?itemName=RamonViladomat.StructLayout
> Added new object types; defined enum flag operators; disable #pragma optimize for Clang

- src/client/headers/shared/containers.hpp
* Fixes the `clear` bug
* Fixes allowing `erase` past the end of the vector
* Makes `reserve` reserve exactly instead of using `grow`
* `resize` doesn't deallocate anymore.
* `grow` uses a different algorithm that scales with capacity (doubles the capacity as long as it's below a `maxGrowth` number)
~~Also I'm now using `Allocator::allocate` instead of `Allocator::reallocate`. If reallocate was using a pool allocator I guess I shouldn't have done that...~~
> Fix and improve auto_array

- src/host/extensions/extensions.cpp
Changing to LoadLibraryExW allows for placing dependencies next to the plugin instead of next to the exe.
If a DLL has dependencies, we need a better mechanism to allow for those dependencies to be loaded rather than placing them next to the exe. [LoadLibraryExW](https://learn.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexw) provides us with search flags that LoadLibrary does not offer. LoadLibrary failure for loading dependencies comes from the fact that we pass in a full path name to it. Windows doesn't attempt to locate the dependencies by searching a well-defined set of directories rather it follows safe dll [searching](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-security). Now it is a good thing that we provided the full …
> Change loadlibraryW to loadLibraryExW for additional flags

- src/host/loader/CommandTypes.hpp
This sizing works for me on `2.14`/`linux64`
> loader: fix sizing of securityStuff for linux64 on new command type
